### ISSUE TITLE
Add new logo

### ISSUE THREAD

**Issue by miguelcouteirorodrigues** [jaruba/channel-logos#2]
Hi,

Would it be possible to add a new logo for "Vodafone TV"? [This](https://cdn.webrazzi.com/uploads/2020/03/vodafone-tv-848_hd.png) would be the logo in question.

Thank you.

**Comment by jaruba** [comment]
There are 2 ways of adding new logos:
- submit the channel logo to [TMDB](https://www.themoviedb.org/)
**or**
- creating a PR to this repository adding the png (with transparent background) logo to the `/custom` folder, the png should be named like the channel, with lowercase characters, replacing space with `_`.  (in ur case `vodafone_tv.png`)

**Comment by miguelcouteirorodrigues** [comment]
I've created the PR. I'm closing this issue.
