### ISSUE TITLE
Question on the app channels

### ISSUE THREAD

**Issue by mystex** [jaruba/channel-logos#6]
I For the logos it appears to work on the sources as well. For instance I have one source defined as Switch and it grabs the Twitch logo. Would we be able to add logos for things like game consoles or generic ones like blueray?

Looking in the repo here I'm probably just not understanding how to get it to show the switch logo. Will see if I can figure it out.

**Comment by mystex** [comment]
I'm an idiot and just needed to rename the source. I am going to look into creating logos for blueray & dvd players if I can figure that part out.

**Comment by jaruba** [comment]
There is a Readme file in the `/custom` folder that explains how to add custom logos to this repository: https://github.com/jaruba/channel-logos/blob/main/custom/README.md
